2017-05-07 02:02:53,277, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:02:53,417, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:02:58,769, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:02:58,770, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:02:58,770, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:02:58,783, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:02:58,791, INFO, ManageParking.py, getParking(21), {'lMVParkingPrice': 15, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x10a362290>, 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 5, 'totalCountOfSpaces': 10}
2017-05-07 02:02:58,791, INFO, ParkingController.py, response_parking(25), get Parking FFC {'lMVParkingPrice': 15, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x10a362290>, 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 5, 'totalCountOfSpaces': 10}
2017-05-07 02:09:01,478, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:09:02,453, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:14:58,092, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:14:58,238, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:15:02,851, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:15:02,851, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:15:02,851, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:15:02,856, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:15:02,862, ERROR, ManageParking.py, getParking(24), Get Parking Info failed
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.remove("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'remove'
2017-05-07 02:15:02,862, ERROR, ParkingController.py, response_parking(14), Error Unable to get customers
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/controllers/ParkingController.py", line 12, in response_parking
    data = getParking()
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.remove("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'remove'
2017-05-07 02:15:02,865, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": null, 
    "status": {
        "code": 500, 
        "message": "get Parking fail", 
        "success": false
    }
}
2017-05-07 02:17:33,774, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:17:33,778, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:17:33,778, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:17:33,787, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:17:33,814, ERROR, ManageParking.py, getParking(24), Get Parking Info failed
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.removeValueForKey("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'remove'
2017-05-07 02:17:33,816, ERROR, ParkingController.py, response_parking(14), Error Unable to get customers
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/controllers/ParkingController.py", line 12, in response_parking
    data = getParking()
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.removeValueForKey("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'remove'
2017-05-07 02:17:33,817, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": null, 
    "status": {
        "code": 500, 
        "message": "get Parking fail", 
        "success": false
    }
}
2017-05-07 02:17:40,136, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:17:40,286, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:17:41,388, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3127, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:17:42,158, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:17:52,238, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:17:52,363, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:17:56,770, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:17:56,771, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:17:56,771, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:17:56,781, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:17:56,788, ERROR, ManageParking.py, getParking(24), Get Parking Info failed
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.removeValueForKey("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'removeValueForKey'
2017-05-07 02:17:56,788, ERROR, ParkingController.py, response_parking(14), Error Unable to get customers
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/backend/controllers/ParkingController.py", line 12, in response_parking
    data = getParking()
  File "/Users/braj/git/ParkingLots/backend/lib/ManageParking.py", line 21, in getParking
    logging.info(postJson.__dict__.removeValueForKey("_sa_instance_state"))
AttributeError: 'dict' object has no attribute 'removeValueForKey'
2017-05-07 02:17:56,791, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": null, 
    "status": {
        "code": 500, 
        "message": "get Parking fail", 
        "success": false
    }
}
2017-05-07 02:19:12,154, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:19:12,292, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:19:39,372, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:19:39,571, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:19:45,323, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:19:45,326, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:19:45,326, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:19:45,340, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:19:45,350, INFO, ManageParking.py, getParking(22), {'lMVParkingPrice': 15, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 5, 'totalCountOfSpaces': 10}
2017-05-07 02:19:45,350, INFO, ParkingController.py, response_parking(25), get Parking FFC {'lMVParkingPrice': 15, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 5, 'totalCountOfSpaces': 10}
2017-05-07 02:19:45,350, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": {
        "_sa_instance_state": "", 
        "lMVOccupied": false, 
        "lMVParkingCount": 5, 
        "lMVParkingPrice": 15, 
        "lotId": 1, 
        "totalCountOfSpaces": 10, 
        "twoWheelerOccupied": false, 
        "twoWheelerParkingCount": 5, 
        "twoWheelerParkingPrice": 12
    }, 
    "status": {
        "code": 200, 
        "message": "success", 
        "success": true
    }
}
2017-05-07 02:24:27,044, INFO, ParkingRoutes.py, addParkingLot(33), The data posted is {'lMVParkingPrice': 16, 'totalCountOfSpaces': 15, 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10}
2017-05-07 02:24:33,502, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:24:33,506, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:24:33,506, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:24:33,519, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:24:33,535, INFO, ManageParking.py, getParking(22), {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:24:33,535, INFO, ParkingController.py, response_parking(25), get Parking FFC {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:24:33,535, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": {
        "_sa_instance_state": "", 
        "lMVOccupied": false, 
        "lMVParkingCount": 5, 
        "lMVParkingPrice": 16, 
        "lotId": 1, 
        "totalCountOfSpaces": 15, 
        "twoWheelerOccupied": false, 
        "twoWheelerParkingCount": 10, 
        "twoWheelerParkingPrice": 12
    }, 
    "status": {
        "code": 200, 
        "message": "success", 
        "success": true
    }
}
2017-05-07 02:26:19,967, INFO, ParkingRoutes.py, addParkingLot(33), The data posted is {'lMVParkingPrice': 16, 'totalCountOfSpaces': 15, 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10}
2017-05-07 02:26:24,988, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:26:24,988, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:26:24,989, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:26:24,993, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:26:24,999, INFO, ManageParking.py, getParking(22), {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:26:24,999, INFO, ParkingController.py, response_parking(25), get Parking FFC {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': False, 'twoWheelerOccupied': False, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:26:25,000, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": {
        "_sa_instance_state": "", 
        "lMVOccupied": false, 
        "lMVParkingCount": 5, 
        "lMVParkingPrice": 16, 
        "lotId": 1, 
        "totalCountOfSpaces": 15, 
        "twoWheelerOccupied": false, 
        "twoWheelerParkingCount": 10, 
        "twoWheelerParkingPrice": 12
    }, 
    "status": {
        "code": 200, 
        "message": "success", 
        "success": true
    }
}
2017-05-07 02:26:47,226, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:26:47,800, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:32:43,195, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:32:43,336, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:32:52,439, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:32:53,234, ERROR, RunApiServer.py, main(27), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:33:06,086, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:33:06,234, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:33:19,342, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:33:20,135, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:33:41,921, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:33:42,060, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:33:49,189, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:33:49,965, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:35:37,043, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:35:37,186, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:35:42,306, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:35:43,073, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:35:50,488, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:35:50,793, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:35:59,923, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:36:00,535, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
2017-05-07 02:36:25,783, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:36:26,022, DEBUG, RunApiServer.py, main(21), Inside Main Run Api Server. Trying to start the API server
2017-05-07 02:36:43,371, DEBUG, ParkingRoutes.py, getRecentCustomers(10), /parkings  GET called
2017-05-07 02:36:43,373, INFO, ParkingController.py, response_parking(10), response customer controller
2017-05-07 02:36:43,374, INFO, ManageParking.py, getParking(16), get Parking Manage head count
2017-05-07 02:36:43,385, INFO, ParkingDao.py, readRowFromTable(8), ParkingDao read row
2017-05-07 02:36:43,399, INFO, ManageParking.py, getParking(22), {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': 0, 'twoWheelerOccupied': 0, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:36:43,399, INFO, ParkingController.py, response_parking(25), get Parking FFC {'lMVParkingPrice': 16, 'lotId': 1, 'lMVParkingCount': 5, 'lMVOccupied': 0, 'twoWheelerOccupied': 0, '_sa_instance_state': '', 'twoWheelerParkingPrice': 12, 'twoWheelerParkingCount': 10, 'totalCountOfSpaces': 15}
2017-05-07 02:36:43,399, DEBUG, ParkingRoutes.py, getRecentCustomers(14), sending  {
    "response": {
        "_sa_instance_state": "", 
        "lMVOccupied": 0, 
        "lMVParkingCount": 5, 
        "lMVParkingPrice": 16, 
        "lotId": 1, 
        "totalCountOfSpaces": 15, 
        "twoWheelerOccupied": 0, 
        "twoWheelerParkingCount": 10, 
        "twoWheelerParkingPrice": 12
    }, 
    "status": {
        "code": 200, 
        "message": "success", 
        "success": true
    }
}
2017-05-07 02:43:34,275, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3115, in run
    sys.exit(3)
SystemExit: 3
2017-05-07 02:43:35,049, ERROR, RunApiServer.py, main(28), An error occurred while trying to start the API server
Traceback (most recent call last):
  File "/Users/braj/git/ParkingLots/RunApiServer.py", line 24, in main
    run(app, host='0.0.0.0', port=PORT, reloader=True)
  File "/Library/Python/2.7/site-packages/bottle.py", line 3075, in run
    sys.exit(p.poll())
SystemExit: 0
